<?xml version="1.0" encoding="UTF-8"?>

<DBError statementIndex="0" name="D:\WebRatio\Projects\WE101\DBScripts\test.sql">
  <ErrorMessage>com.webratio.commons.db.CompositeException: SQL script execution failed : D:\WebRatio\Projects\WE101\DBScripts\test.sql</ErrorMessage>
  <Comment></Comment>
  <Statement> SELECT count(*) FROM WEBRATIO.VEHICLE_CROSSWALK1 WHERE CROSSWALK_OID = 5</Statement>
  <ErrorMessage>com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'webratio.vehicle_crosswalk1' doesn't exist</ErrorMessage>
  <StackTrace>com.webratio.commons.db.DBException: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'webratio.vehicle_crosswalk1' doesn't exist
	at com.webratio.commons.db.utils.DBUtils.execute(DBUtils.java:529)
	at com.webratio.commons.db.utils.DBUtils.executeScriptFiles(DBUtils.java:442)
	at com.webratio.commons.db.utils.DBUtils.main(DBUtils.java:257)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'webratio.vehicle_crosswalk1' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:408)
	at com.mysql.jdbc.Util.getInstance(Util.java:383)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1062)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4158)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2615)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2776)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2834)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2783)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:908)
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:788)
	at com.webratio.commons.db.utils.DBUtils.execute(DBUtils.java:523)
	... 2 more
</StackTrace></DBError>